(defun parse-input (input)
  (let ((read-input (uiop:read-file-lines input)))
    read-input))

(defun get-x-y (x y input)
  (let* ((line (nth y input))
         (char (char line x)))
    char))

(defun get-around-x-y (x y input)
  (let* ((line (nth y input))
         (line-length (length line))
         (input-length (length input)))
    (cond ((and (= x 0) ; 0:0
                (= y 0))
           (list (get-x-y (1+ x) y input)
                 (get-x-y (1+ x) (1+ y) input)
                 (get-x-y x (1+ y) input)))
          ((and (= x 0) ; 0:9
                (= y (1- input-length)))
           (list (get-x-y x (1- y) input)
                 (get-x-y (1+ x) (1- y) input)
                 (get-x-y (1+ x) y input)))
          ((and (= x (1- line-length)) ; 9:0
                (= y 0))
           (list (get-x-y x (1+ y) input)
                 (get-x-y (1- x) (1+ y) input)
                 (get-x-y (1- x) y input)))
          ((and (= x (1- line-length)) ; 9:9
                (= y (1- input-length)))
           (list (get-x-y (1- x) y input)
                 (get-x-y (1- x) (1- y) input)
                 (get-x-y x (1- y) input)))
          ((= y 0)
           (list (get-x-y (1+ x) y input)
                 (get-x-y (1+ x) (1+ y) input)
                 (get-x-y x (1+ y) input)
                 (get-x-y (1- x) (1+ y) input)
                 (get-x-y (1- x) y input)))
          ((= y (1- input-length))
           (list (get-x-y (1- x) y input)
                 (get-x-y (1- x) (1- y) input)
                 (get-x-y x (1- y) input)
                 (get-x-y (1+ x) (1- y) input)
                 (get-x-y (1+ x) y input)))
          ((= x 0)
           (list (get-x-y x (1- y) input)
                 (get-x-y (1+ x) (1- y) input)
                 (get-x-y (1+ x) y input)
                 (get-x-y (1+ x) (1+ y) input)
                 (get-x-y x (1+ y) input)))
          ((= x (1- line-length))
           (list (get-x-y x (1+ y) input)
                 (get-x-y (1- x) (1+ y) input)
                 (get-x-y (1- x) y input)
                 (get-x-y (1- x) (1- y) input)
                 (get-x-y x (1- y) input)))
          (t
           (list (get-x-y x (1- y) input)
                 (get-x-y (1+ x) (1- y) input)
                 (get-x-y (1+ x) y input)
                 (get-x-y (1+ x) (1+ y) input)
                 (get-x-y x (1+ y) input)
                 (get-x-y (1- x) (1+ y) input)
                 (get-x-y (1- x) y input)
                 (get-x-y (1- x) (1- y) input))))))

(defun paper-roll-accessible-p (around)
  (let ((paper-rolls (count #\@ around)))
    (if (< paper-rolls 4)
        t)))

(defun part1 (input)
  (length (loop with input = (parse-input input)
                for line in input
                for line-length = (length line)
                for y from 0
                nconc (loop for c across line
                            for x from 0
                            for center = (get-x-y x y input)
                            for around = (get-around-x-y x y input)
                            if (and (char= center #\@)
                                    (paper-roll-accessible-p around))
                              collect t))))
