(let ((input (split-string (f-read-text "1.input.txt")))
      (s)
      (first)
      (last)
      (n)
      (output 0))
  (dolist (line input)
    (setq s (split-string (mapconcat 'identity (split-string line "[a-z]" t))
			  "" t)
	  first (car s)
	  last (car (last s))
	  n (string-to-number (concat first last))
	  output (+ output n)))
  (print output))
